#!/usr/bin/env python3
"""
make_voice.py — one spoken line, baked into the firmware.

  python3 robot/tools/make_voice.py "I saw that."
  python3 robot/tools/make_voice.py --voice Samantha "I saw that."
  python3 robot/tools/make_voice.py --wav recorded.wav
  python3 robot/tools/make_voice.py --list        # the voices on this Mac

Writes robot/firmware/cores3_sidekick/voice.h, then reflash. `EVT SAY` plays it.

NO SD CARD. The line lives in flash as a byte array next to the sketch: the
card is one more thing to be missing, unreadable or full in front of an
audience, and it buys nothing here. Three seconds at 16 kHz is 96 KB against
3 MB of program space.

16 kHz MONO, NOT BECAUSE IT IS ENOUGH but because the speaker is 1 W in a
printed shell -- there is nothing above 8 kHz for it to reproduce, and the
higher rates only spend flash. It comes out a little thin, which is the right
kind of wrong: a small machine with a small voice reads as the machine
speaking. The same line through a PA reads as narration about it.

WHERE TO USE IT. At the end, after the music has stopped, with people close.
The point of putting the voice in the body is that the sound is LOCATED there,
and that only survives while nothing louder is playing.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "robot", "firmware", "cores3_sidekick", "voice.h")
RATE = 16000


def need(prog):
    if not shutil.which(prog):
        sys.exit(f"{prog} not found. brew install {prog}")


def main():
    ap = argparse.ArgumentParser(description="bake one spoken line into the firmware")
    ap.add_argument("text", nargs="?", help="what it says")
    ap.add_argument("--wav", help="use this audio file instead of speaking text")
    ap.add_argument("--voice", default="Samantha", help="macOS `say` voice")
    ap.add_argument("--rate", type=int, default=170, help="words per minute")
    ap.add_argument("--list", action="store_true", help="list the voices and stop")
    a = ap.parse_args()

    if a.list:
        subprocess.run(["say", "-v", "?"])
        return 0
    if not (a.text or a.wav):
        ap.error("give it a line, or --wav")

    need("ffmpeg")
    with tempfile.TemporaryDirectory() as tmp:
        src = a.wav
        if not src:
            need("say")
            src = os.path.join(tmp, "raw.aiff")
            subprocess.run(["say", "-v", a.voice, "-r", str(a.rate),
                            "-o", src, a.text], check=True)
        wav = os.path.join(tmp, "out.wav")
        # NORMALISE, then convert. A quiet line on a 1 W speaker in a room with
        # people in it is a line nobody hears, and there is no volume left to
        # find afterwards -- the amplifier is already at 100.
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", src,
                        "-af", "loudnorm=I=-14:TP=-1.5",
                        "-ar", str(RATE), "-ac", "1",
                        "-c:a", "pcm_s16le", wav], check=True)
        data = open(wav, "rb").read()

    kb = len(data) / 1024
    secs = (len(data) - 44) / (RATE * 2)
    if kb > 400:
        sys.exit(f"{kb:.0f} KB is too much to bake in. Shorten the line.")

    with open(OUT, "w") as f:
        f.write("// Generated by robot/tools/make_voice.py -- do not hand-edit.\n")
        f.write(f"// {secs:.2f}s, {RATE} Hz mono, {kb:.0f} KB\n")
        if a.text:
            f.write(f"// says: {a.text!r}\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"static const uint8_t VOICE_WAV[{len(data)}] PROGMEM = {{\n")
        for i in range(0, len(data), 16):
            f.write("  " + ",".join(str(b) for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"{OUT}\n  {secs:.2f}s, {kb:.0f} KB. Reflash, then `EVT SAY`.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
